aseURL = 'https://svenyang.github.io/photo'
languageCode = 'zh-CN'
title = 'oo'


[module]
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]
  [main]
    name = "test"
    weight = 1

[params]
    showDate = 'Yes'